sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: HLY999113
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: <KEY>
    secret-key-secret: <KEY>
    bucket-name: sky-take-out
